In [ ]:
 #1)Create a NumPy array 'arr' of integers from 0 to 5 and print its data type
import numpy as np
arr=np.array([0,1,2,3,4,5])
arr


array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.dtype

dtype('int32')

In [ ]:
#2) Given a NumPy array 'arr', check if its data type is float64
#arr = np.array([1.5, 2.6, 3.7])
arr1=np.array([1.5, 2.6, 3.7])
arr1.dtype


dtype('float64')

In [ ]:
#3) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
a=np.array([4+5j,8+7j,8+1j],dtype = complex)
a

array([4.+5.j, 8.+7.j, 8.+1.j])

In [ ]:
a.dtype


dtype('complex128')

In [ ]:
#4) Convert an existing NumPy array 'arr' of integers to float32 data type
arr2=np.array([1,2,3,4])
arr3=arr2.astype(np.float32)
arr3

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
arr3.dtype

dtype('float32')

In [ ]:
#5) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision
p=np.array([1.2,3.5,6.8])
p.dtype

dtype('float64')

In [ ]:
q=p.astype(np.float32)
q

array([1.2, 3.5, 6.8], dtype=float32)

In [ ]:
#6) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
#type
import numpy as np

def array_attributes(arr):
    shape=arr.shape
    size=arr.size
    data_type=arr.dtype
    return shape,size,data_type

a= array_attributes(np.array([[1,2,3],[5,4,9]]))
a


((2, 3), 6, dtype('int32'))

In [ ]:
#7)Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

def array_dimension(arr1):
    dimension=arr1.ndim
    return dimension
b=array_dimension(np.array([[[1,2,3],[5,4,9]]]))
b

3

In [ ]:
'''8). Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes.'''
def item_size_info(arr2):
    item_size=arr2.itemsize
    size_in_byte=arr2.nbytes
    return item_size,size_in_byte
    
a= item_size_info(np.random.randint(1,3,(2,2)))
a
    


(4, 16)

In [ ]:
'''9) Create a function array_strides that takes a NumPy array as input and returns the strides of the array.'''

def array_strides(str):
    strides=str.strides
    return strides
a=array_strides(np.random.randint(1,3,(2,2)))
a
   

(8, 4)

In [ ]:
'''10) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
and strides of the array.'''

def shape_stride_relationship(shape_stride):
    shape=shape_stride.shape
    
    strides=shape_stride.strides
    return shape,strides
a=array_strides(np.random.randint(1,3,(2,2)))
a
  
    
    


(8, 4)

In [ ]:
'''11)1. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements.'''

def create_zeros_array(n):
    return np.zeros(n)
zeros=create_zeros_array(5)
zeros

array([0., 0., 0., 0., 0.])

In [ ]:
'''12)Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
NumPy array filled with ones of size `rows x cols`.'''
import numpy as np
def create_ones_matrix(i,j):
    return np.ones([i,j])
ones=create_ones_matrix(3,4)
ones



array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
ones.ndim


2

In [ ]:
'''13) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`'''
def generate_range_array(start,stop,step):
    return np.arange(start,stop,step)
range1=generate_range_array(1,20,2)
range1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
'''14)Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive).'''

def generate_linear_space(start,stop,step):
    return np.linspace(start,stop,step)
range2=generate_linear_space(1.1,2.2,5)
range2

array([1.1  , 1.375, 1.65 , 1.925, 2.2  ])

In [ ]:
'''15)Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye'''

def create_identity_matrix(n):
    return np.eye(n)
identity=create_identity_matrix(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
'''16) Write a function that takes a Python list and converts it into a NumPy array'''
l=[1,2,3,4.5,"pragati",True]
np.array(l)

array(['1', '2', '3', '4.5', 'pragati', 'True'], dtype='<U32')

In [ ]:
'''17) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data.'''
import numpy as np
arr=np.array([5,6,7,8,10])
print("orignal array is",arr)
new_array=arr.view()
print("new array is",new_array)

orignal array is [ 5  6  7  8 10]
new array is [ 5  6  7  8 10]


In [ ]:
'''18) Write a function that takes two NumPy arrays and concatenates them along a specified axis.'''

def concatenate_arary(array1,array2,axis=0):
    return np.concatenate((array1,array2),axis=0)
array1=np.array([1,2,3,4])
array2=np.array([5,6,7])
result=concatenate_arary(array1,array2,axis=0)
result

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
'''19) Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate'''

array1=np.array([[1,2,3],[4,5,6]])

array2=np.array([[7,8],[9,10]])
result =np.concatenate((array1, array2), axis=1)
result

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6,  9, 10]])

In [ ]:
'''20) Write a function that vertically stacks multiple NumPy arrays given as a list'''
import numpy as np
def vertically_stacks(array):
    return np.vstack(array)
array1=np.array([[1,2,3],[4,5,6],[8,10,55]])
verticalstack=vertically_stacks(array1)
verticalstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8, 10, 55]])

In [ ]:
'''21) Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size'''
import numpy as np
def int_array(start,end,step):
    return np.arange(start,end+1,step,dtype=int)
result=int_array(0,10,2)
result



array([ 0,  2,  4,  6,  8, 10])

In [ ]:
'''22). Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive)'''
def array():
    return np.linspace(0,1,10)
b= array()
b



array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
'''23) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
1000 (inclusive)'''
def log_fun():
    return np.logspace(1,1000,5)
fun=log_fun()
fun

C:\Users\praga\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\function_base.py:284: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [ ]:
#!pip install pandas





In [ ]:
'''24) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100.'''
import numpy as np
import pandas as pd
array=np.random.randint(1, 101, size=(5, 3))
df=pd.DataFrame(array,columns=['col_1','col_2','col_3'])
print(df) 
                       

   col_1  col_2  col_3
0     40     78     37
1     82     98     95
2      5     35     17
3     38     51     48
4     69     78     71


In [64]:
'''25) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame'''
import numpy as np
import pandas as pd
def replace_negative(df1,column):
    
    df1[column] = np.where(df1[column] <0, 0, df1[column])
    return df1
info={
    'd1':[1,2,-4,-9],
    'd2':[5,-10,3,-8]
}
df1=pd.DataFrame(info)
print(df1)
df1=replace_negative(df1,'d1')
df1
    

   d1  d2
0   1   5
1   2 -10
2  -4   3
3  -9  -8


d1  d2
0   1   5
1   2 -10
2   0   3
3   0  -8

In [ ]:
'''26)6. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])'''
arr = np.array([10, 20, 30, 40, 50])
arr2=arr[3]
arr2


40

In [ ]:
'''27) Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],


                   [4, 5, 6],


                   [7, 8, 9]])'''
import numpy as np
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr=arr_2d[1,2]
arr

6

In [ ]:
'''28) Using boolean indexing, extract elements greater than 5 from the given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])''' 
arr = np.array([3, 8, 2, 10, 5, 7])
max_5=arr>5
greater_than_five=arr[max_5]
print(greater_than_five)



[ 8 10  7]


In [ ]:
'''29) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])'''
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5]

array([3, 4, 5])

In [ ]:
'''30) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])'''

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[0:2,1:3]




array([[2, 3],
       [5, 6]])

In [ ]:
'''31).Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
provided in another array.'''

import numpy as np
def extract_element(arr,indices):
    extracted_elements =arr[indices[:, 0], indices[:, 1]]
    return extracted_elements
arr=np.array([[2,3,4],
             [8,5,6],
             [7,8,3]])
indice=np.array([[0,2],[1,2],[2,1]])
result=extract_element(arr,indice)
result

array([4, 6, 8])

In [ ]:
'''32). Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing'''

def greater_than_a_threshold(array,threshold):
    a= array>threshold
    b=array[a]
    return b

array1=np.array([1,2,9,8,10,15,20])
threshold=6
result=greater_than_a_threshold(array1,threshold)
result




array([ 9,  8, 10, 15, 20])

In [ ]:
'''33) Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension'''
import numpy as np
def extract(array,inx1,inx2,inx3):
    if (len(inx1)!=len(inx2) or len(inx2)!=len(inx3)):
        print("index array must have same length")
    
    
    inx1= np.asarray(inx1)
    inx2= np.asarray(inx2)
    inx3= np.asarray(inx3)
    extreacted_element=array[inx1,inx2,inx3]
    return extreacted_element

array1=np.random.rand(3,3,3)
print(array1)

inx1= [0,1,2]
inx2= [1,2,0]
inx3= [2,1,1]

result=extract(array1,inx1,inx2,inx3)
print("extracted element")
print(result)
        
    



[[[0.10982074 0.47629675 0.49569613]
  [0.47850416 0.68582158 0.89742191]
  [0.9652992  0.01367923 0.47834072]]

 [[0.05201605 0.64911874 0.19327378]
  [0.19313664 0.25892061 0.80250792]
  [0.78514721 0.11270084 0.7440933 ]]

 [[0.45821312 0.3767358  0.68341126]
  [0.26907883 0.18706846 0.74448962]
  [0.75649657 0.90864534 0.86209917]]]
extracted element
[0.89742191 0.11270084 0.3767358 ]


In [75]:
'''34) Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing.'''
import numpy as np
def conditions(arr, condition1, condition2):
    a = arr[(condition1) & (condition2)]
    return a


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

condition1 = arr % 2 == 0

condition2 = arr > 5

result = conditions(arr, condition1, condition2)
print(result)


[6 8]


In [70]:
'''35)Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays'''

import numpy as np
def extract(array,row,column):
    if len(row)!=len(column):
        print("index array must have same length")
        return None
        
    row= np.asarray(row)
    column= np.asarray(column)
    extracte_element=array[row,column]
    return extracte_element
    
array=np.random.randint(1,20,size=(3,3))
print(array)
row= [0,1,2]
column= [1,2,0]
result=extract(array,row,column)
print("extracted elements")
print(result)

[[ 6 19  6]
 [ 9 19 19]
 [12  2 18]]
extracted elements
[19 19 12]


In [ ]:
'''36). Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting'''

In [ ]:
import numpy as np
arr_1=np.random.randint(1,3,(3,3))
arr_1
a=np.array([5])
b=arr_1+a
b


array([[7, 6, 7],
       [6, 7, 6],
       [7, 6, 7]])

In [ ]:
'''37) Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting'''
arr_1=np.random.randint(1,3,(1,3))
print("array_1",arr_1)
arr_2=np.random.randint(1,3,(3,4))
print("array_2",arr_2)
b=arr_1 @ arr_2
print("multiplication is",b)


array_1 [[1 1 1]]
array_2 [[1 2 1 2]
 [1 2 2 1]
 [1 2 1 2]]
multiplication is [[3 6 4 5]]


In [ ]:
'''38). Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting.'''
import numpy as np
arr1=np.array([1,4,3,5]).reshape(1,4)
arr1.shape
arr2=np.array([[1,2,3,],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
reshape_arr2=arr2.reshape(4,3)
reshape_arr2.shape
result=reshape_arr2+arr1.T
result


array([[ 2,  3,  4],
       [ 8,  9, 10],
       [10, 11, 12],
       [15, 16, 17]])

In [ ]:
'''39) Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
broadcasting.'''
import numpy as np
arr1=np.array([1,4,3]).reshape(3,1)
print("array1",arr1)
arr2=np.array([1,4,3]).reshape(1,3)
print("array_2",arr2)
add=arr1+arr2
add

array1 [[1]
 [4]
 [3]]
array_2 [[1 4 3]]


array([[2, 5, 4],
       [5, 8, 7],
       [4, 7, 6]])

In [ ]:
'''40)Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility.'''
arr1=np.array([[1,4,3],[2,3,6]]).reshape(2,3)
arr2=np.array([[1,4],[2,3]]).reshape(2,2)
arr2_reshape=arr2[:, :, np.newaxis]
mult=arr1 * arr2_reshape
mult



array([[[ 1,  4,  3],
        [ 8, 12, 24]],

       [[ 2,  8,  6],
        [ 6,  9, 18]]])

In [ ]:
'''41) Calculate column wise mean for the given array

arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_wisw_mean=np.mean(arr,axis=0)
print("column wise mean is:",column_wisw_mean)


column wise mean is: [2.5 3.5 4.5]


In [ ]:
'''42) Find maximum value in each row of the given array
arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_value=np.max(arr)
print("maximum value is:",max_value)

maximum value is: 6


In [ ]:
'''43) For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices=np.argmax(arr,axis=0)
max_indices


array([1, 1, 1], dtype=int64)

In [61]:
'''44) For the given array, apply custom function to calculate moving sum along rows
arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
   

In [ ]:
'''45) In the given array, check if all elements in each column are even
arr = np.array([[2, 4, 6], [3, 5, 7]])'''

arr = np.array([[2, 4, 6], [3, 5, 7]])
even=np.all(arr %2 ==0 ,axis=0)
even

array([False, False, False])

In [ ]:
'''46) Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])'''

original_array = np.array([1, 2, 3, 4, 5, 6])
print("orignal array is:",original_array)
reshaped_matrix=original_array.reshape(2,3)
print("reshaped matrix is:"
      ,reshaped_matrix)



orignal array is: [1 2 3 4 5 6]
reshaped matrix is: [[1 2 3]
 [4 5 6]]


In [ ]:
'''47)Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])'''

def flattened_array(arr):
    return arr.flatten()
result=flattened_array(np.array([[1, 2, 3], 
                                 [4, 5, 6]]))
result



array([1, 2, 3, 4, 5, 6])

In [ ]:
'''48)Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]]),
array2 = np.array([[5, 6], [7, 8]])'''

def array(arr1,arr2,axis=0):
    concatenated_array=np.concatenate((arr1,arr2),axis=axis)
    return concatenated_array

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result=array(array1,array2,axis=0)
result


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
'''49) Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])'''
import numpy as np

def split_array(array,index_no,axis=0):
    split_arrays=np.array_split(array,index_no,axis=axis)
    
    return split_arrays

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("original array:")
print(original_array)

split_array1= split_array(original_array, 3 ,axis=1)
print("row wise spliting")
print(split_array1)

split_array0= split_array(original_array, 2 ,axis=0)
print("column wise spliting")
print(split_array0)





original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
row wise spliting
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
column wise spliting
[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [58]:
'''50) Write a function that inserts and then deletes elements from a given array at specified indices
original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]
'''
import numpy as np
def fun_operation(original_array,indices_insert,values_insert,delete_indices):
    original_array=np.insert(original_array,indices_insert,values_insert)
    original_array=np.delete(original_array,delete_indices)
    return original_array

original_array=np.array([1, 2, 3, 4, 5])
indices_insert=[2,3]
values_insert=[10,20]
delete_indices=[0,1]

result=fun_operation(original_array,indices_insert,values_insert,delete_indices)
print(result)
    

    



[10  3 20  4  5]


In [ ]:
'''51)Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`'''

arr1=np.random.randint(1,3,size=(3,4))
print(arr1)

arr2=np.random.randint(1,10,size=(3,4))
print(arr2)

add=arr1+arr2
print("addition is:")
print(add)

[[2 2 2 2]
 [1 1 2 2]
 [2 2 1 2]]
[[5 2 1 6]
 [8 3 7 4]
 [5 4 6 9]]
addition is:
[[ 7  4  3  8]
 [ 9  4  9  6]
 [ 7  6  7 11]]


In [ ]:
'''52)Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise'''

arr1=np.arange(10,0,-1)
print(arr1)
arr2=np.arange(1,11)
print(arr2)

subtract=arr1-arr2
print("subtraction is:")
print(subtract)


[10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10]
subtraction is:
[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
'''53) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2'''

arr1=np.random.randint(1,3,size=(3,3))
print("array1")
print(arr1)

arr2=np.random.randint(1,5,size=(3,3))
print("array2")
print(arr2)

multiplication=arr1 @ arr2
print("multiplication is:")
multiplication


array1
[[1 2 2]
 [2 2 1]
 [2 2 2]]
array2
[[1 1 2]
 [4 1 4]
 [1 4 3]]
multiplication is:


array([[11, 11, 16],
       [11,  8, 15],
       [12, 12, 18]])

In [ ]:
'''54) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`'''


arr1=np.arange(2,11,2)

print("array_1",arr1)
arr2=np.arange(1,6)
print("array_2",arr2)
division=arr1/arr2
print("division is:",division)
    


array_1 [ 2  4  6  8 10]
array_2 [1 2 3 4 5]
division is: [2. 2. 2. 2. 2.]


In [ ]:
'''55) Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise'''

arr1= np.arange(1,6)
print("array_1 is",arr1)

arr2=arr1[::-1]
print("arary_2 is",arr2)

power= arr1**arr2
print("power is ",power)

array_1 is [1 2 3 4 5]
arary_2 is [5 4 3 2 1]
power is  [ 1 16 27 16  5]


In [11]:
'''56). Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])'''

import numpy as np
def count_occurrences(arr,substring):
    
       if not np.issubdtype(arr.dtype,np.str_):
        raise TypeError("it should be string")
         
   
       count=sum(s.count(substring) for s in arr)
       return count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring="hello"

result=count_occurrences(arr,substring)
print("occurrences is")
result

occurrences is


3

In [12]:
'''57) Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])'''

def extracts_uppercase(arr):
    if not np.issubdtype(arr.dtype,np.str_):
        raise TypeError("it should be string")
        
    uppercase = np.char.upper(arr)  
    return uppercase
arr= np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result=extracts_uppercase(arr)
result
         
    



array(['HELLO', 'WORLD', 'OPENAI', 'GPT'], dtype='<U6')

In [61]:
'''58) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''
'''58) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''
import numpy as np

def replace_string(arr, string1, string2):

    if not np.issubdtype(arr.dtype, np.str_):
        raise TypeError("All elements in the array should be strings")
    
    
    replaced_arr = np.array([s.replace(string1, string2) for s in arr])
    return replaced_arr

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
string1 = 'apple'
string2 = 'mango'

result = replace_string(arr, string1, string2)
print(result)  


['mango' 'banana' 'grape' 'pinemango']


In [62]:
'''59) Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])
'''

def concatenates_strings(arr1,arr2):
    if (arr1.shape==arr2.shape):
        return np.char.add(arr1,arr2)
    else:
        print("string should have same shape")
        
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result=concatenates_strings(arr1,arr2)
result

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [64]:
'''60) Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''

def longest_string(arr):
    maximum_string=max(len(a)for a in arr)
    return maximum_string
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result=longest_string(arr)
result

9

In [70]:
'''61).Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions.'''

import numpy as np
dataset=np.random.randint(1,1001,size=100)
print("dataset is:",dataset)

print("mean of dataset:")
mean=np.mean(dataset)
print(mean)
print("median of dataset is:")
median=np.median(dataset)
print(median)
print("variance of dataset is:")
variance=np.var(dataset)
print(variance)
print("standard deviation of dataset is:")
std_dev=np.std(dataset)
print(std_dev)

dataset is: [ 428  689  824  675  908  779   49  609  749    9  286  643  249  373
  759  122  747  651  388  913  413   87  931  260  326  863  366  274
  661  352  694  260  797  877  971  628  926  881  378  483  372  486
  813  645  685  128  408  981  374  183  591  142   65   40  898  247
  600  133  402  928  928  440  397 1000  485  519  437  239  758  485
  479  143  236  644    2  112  685  959  723  153  509  781  853  741
  812  440  229  911  791  479  988  604  730  891  525  137   26  135
  219  288]
mean of dataset:
523.12
median of dataset is:
497.5
variance of dataset is:
82534.00559999999
standard deviation of dataset is:
287.28732237953


In [76]:
'''62) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset.'''

dataset=np.random.randint(1,101,size=50)
print(dataset)
_25th_percentile=np.percentile(dataset,25)
print("25th percentiles is:",_25th_percentile)

_75th_percentile=np.percentile(dataset,75)
print("75th percentiles is:",_75th_percentile)


[ 89  93  65   3  35  41  70 100  43   3  66  92  32  93  91  11  25  81
  92   2  73  56  62  37  34  74  33  54  17  36  76  59   2   7  80  91
  89  71  39  29  40  55  37  65  84  64   2  91  56  82]
25th percentiles is 34.25
75th percentiles is 80.75


In [81]:
'''63). Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function'''

var1=np.array([1,2,3,4,5])
var2=np.array([6,7,8,9,10])
correlation_coefficient=np.corrcoef(var1,var2)[0,1]
print("correlation coefficient is:",correlation_coefficient)

correlation coefficient is: 0.9999999999999999


In [44]:
'''64) Create two matrices and perform matrix multiplication using NumPy's `dot` function.'''
import numpy.matlib as nm

matrix_1=nm.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

matrix_2=nm.array([[7,8,9],
                  [4,5,6],
                  [10,11,52]])

dot_product=np.dot(matrix_1,matrix_2)
print(dot_product)

[[ 45  51 177]
 [108 123 378]
 [171 195 579]]


In [85]:
'''65) Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.'''
import numpy as np

array=np.random.randint(1,1001,size=50)
print("array",array)
percentiles=np.percentile(array,[10,50,90])
print("10th percentiles",percentiles[0])
print("50th percentiles",percentiles[1])
print("90th percentiles",percentiles[2])

quartiles=np.percentile(array,[25,50,75])
print("first quartile:",quartiles[0])
print("third quartile:",quartiles[2])

array [125 344 206 107 948  56 441  30 409 181  29 303 902 935 523  23 131 518
 328 192 655  23 913 239 523 483  85 463 712 339 451 337 343 896   5 894
 500 885 802 925 744 139  68 658 524 433 954 260  15 910]
10th percentiles 29.9
50th percentiles 421.0
90th percentiles 910.3
first quartile: 149.5
third quartile: 698.5


In [92]:
'''66). Create a NumPy array of integers and find the index of a specific element'''
array=np.array([1,2,3,4,5,6,7,8,9,10])
element=7
print("element to find index",element)
index=np.where(array==element)[0]
print("index of a element",index)

element to find index 7
index of a element [6]


In [98]:
'''67) Generate a random NumPy array and sort it in ascending order.'''
array=np.random.randint(1,10,size=20)
print (array)
ascending_order=np.sort(array)
print("ascending order of array is:",ascending_order)

[7 6 6 3 3 6 7 5 1 3 3 1 1 9 1 5 4 4 3 8]
ascending order of array is: [1 1 1 1 3 3 3 3 3 4 4 5 5 6 6 6 7 7 8 9]


In [100]:
'''68) Filter elements >20  in the given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])'''

arr = np.array([12, 25, 6, 42, 8, 30])
a=arr[arr>20]
print("elements >20: ",a)

elements >20:  [25 42 30]


In [102]:
'''69)Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])'''

arr = np.array([1, 5, 8, 12, 15])
a=arr[arr%3==0]
print("elements which are divisible by 3:",a)

elements which are divisible by 3: [12 15]


In [104]:
'''70)Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])'''
arr = np.array([10, 20, 30, 40, 50])
result=arr[(arr>=20)&(arr<=40)]
print("elements which are ≥ 20 and ≤ 40:",result)

elements which are ≥ 20 and ≤ 40: [20 30 40]


In [105]:
'''71). For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])'''

arr = np.array([1, 2, 3])
byte_order=arr.dtype.byteorder
print("byte order is:",byte_order)

byte order is: =


In [109]:
'''72) For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)'''

arr = np.array([1, 2, 3], dtype=np.int32)
print("array",arr)

byte_swapping=arr.byteswap(True)
print("byte swapping:",byte_swapping)


array [1 2 3]
byte swapping: [16777216 33554432 50331648]


In [121]:
'''73) For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)'''
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print("array",arr)
byte_order=arr.dtype.byteorder
print("byte order is:",byte_order)

byte_swapping =arr.byteswap().newbyteorder()
print("byte swapping:",byte_swapping)
print("byte order after swapping:",byte_swapping.dtype.byteorder)


array [1 2 3]
byte order is: =
byte swapping: [1 2 3]
byte order after swapping: >


In [12]:
'''74) For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()
arr = np.array([1, 2, 3], dtype=np.int32)'''

import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr)



system_endianness='little' if np.little_endian else 'big'

if system_endianness=='little':
     swapped_array = arr.byteswap().newbyteorder()
else:
    swapped_array
print("swapped array is",swapped_array)    
    




[1 2 3]
swapped array is [1 2 3]


In [13]:
'''75) For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder
arr = np.array([1, 2, 3], dtype=np.int32)'''

arr = np.array([1, 2, 3], dtype=np.int32)
print(arr)
array_byteorder = arr.dtype.byteorder
if array_byteorder == '=' or \
   (array_byteorder == '<' and system_endianness == 'little') or \
   (array_byteorder == '>' and system_endianness == 'big'):
    
    swapped_arr = arr
else:
    
    swapped_arr = arr.byteswap().newbyteorder()
print("swapped array",swapped_arr)




[1 2 3]
swapped array [1 2 3]


In [16]:
'''76)Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.'''

arr1=np.arange(1,11)
print("array 1:",arr1)
copy_ary=arr1.copy()
copy_ary[0]=100
print("copy array:",copy_ary)
print("array1 after modification:",arr1)

array 1: [ 1  2  3  4  5  6  7  8  9 10]
copy array: [100   2   3   4   5   6   7   8   9  10]
array1 after modification: [ 1  2  3  4  5  6  7  8  9 10]


In [42]:
'''77). Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix'''
import numpy.matlib as nm
matrix=nm.random.randint(0,10,(3,3))
print(matrix)
view_slice=matrix[2:,1:]
view_slice[0,1]=20
print("Modify an element in `view_slice",view_slice)
print("matrix after modification",matrix)

[[0 6 0]
 [1 3 0]
 [2 9 4]]
Modify an element in `view_slice [[ 9 20]]
matrix after modification [[ 0  6  0]
 [ 1  3  0]
 [ 2  9 20]]


In [25]:
'''78) Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`'''

array=np.arange(1,13).reshape(4,3)
print(array)
view_b=array[1:,2:]
view_b+=5
print("extract slice view_b",view_b)
print("array after modification",array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
extract slice view_b [[11]
 [14]
 [17]]
array after modification [[ 1  2  3]
 [ 4  5 11]
 [ 7  8 14]
 [10 11 17]]


In [28]:
'''79)Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`'''

orig_array=np.arange(1,9).reshape(2,4)
print("original array",orig_array)
reshaped_view=orig_array.reshape(4,2)
print("reshaped view",reshaped_view)

reshaped_view[1,1]=18
print("orignal array after modification",orig_array)

original array [[1 2 3 4]
 [5 6 7 8]]
reshaped view [[1 2]
 [3 4]
 [5 6]
 [7 8]]
orignal array after modification [[ 1  2  3 18]
 [ 5  6  7  8]]


In [39]:
'''80) Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data'''

data=np.random.randint(1,10,size=(3,4))
print(data)
data_copy=data[data>5].copy()
print("element greater than five",data_copy)
data_copy[0]= 10

print("data after modification",data)

[[1 6 7 8]
 [2 4 9 7]
 [4 7 1 2]]
element greater than five [6 7 8 9 7 7]
data after modification [[1 6 7 8]
 [2 4 9 7]
 [4 7 1 2]]


In [46]:
'''81)Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them'''

import numpy.matlib as np
A=np.array([[1,2,3],
           [4,5,6]])
print("matrixA",A)
B=np.array([[4,10,11],
           [7,18,96]])
print("matrixB",B)
#addition
add=A+B
print("addition is:",add)
#subtraction
sub=A-B
print("subtraction is:",sub)


matrixA [[1 2 3]
 [4 5 6]]
matrixB [[ 4 10 11]
 [ 7 18 96]]
addition is: [[  5  12  14]
 [ 11  23 102]]
subtraction is: [[ -3  -8  -8]
 [ -3 -13 -90]]


In [47]:
'''82) Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication'''

C=np.random.randint(1,10,size=(3,2))
print(C)
D=np.random.randint(1,10,size=(2,4))
print(D)
#matrix multiplication
mult=C@D
print("matrix multiplication is;",mult)


[[9 2]
 [4 4]
 [6 2]]
[[9 5 3 6]
 [4 9 1 6]]
matrix multiplication is; [[89 63 29 66]
 [52 56 16 48]
 [62 48 20 48]]


In [48]:
'''83) Create a matrix `E` and find its transpose'''
E=np.array([1,2,3,4,5])
transpose=E.T
print("transpose is:",transpose)

transpose is: [1 2 3 4 5]


In [56]:
'''84) Generate a square matrix `F` and compute its determinant.
'''
import numpy.matlib as nm
F=np.array([[1, 2, 3],
              [4, 8, 6],
              [7, 8, 9]])
determinant=np.linalg.det(F)
print("determinant is:",determinant)

determinant is: -36.0


In [57]:
'''85) Create a square matrix `G` and find its inverse.'''
G=np.array([[1, 2, 3],
              [4, 8, 6],
              [7, 8, 9]])
inverse=np.linalg.inv(G)
print("inverse is:",inverse)



inverse is: [[-0.66666667 -0.16666667  0.33333333]
 [-0.16666667  0.33333333 -0.16666667]
 [ 0.66666667 -0.16666667  0.        ]]
